service: serverless-typescript-template

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage}
  region: ${opt:region}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  getExampleTable:
    handler: src/handlers/getTable.handler
    events:
      - http:
          path: /table
          method: get
          cors: true
    iamRoleStatements:
      - ${file(./iam/ExampleTableIAM.yml):ExampleTableGET}

resources:
  Resources:
    ExampleTable: ${file(./resources/ExampleTable.yml):ExampleTable}

custom:
  webpack:
    excludeFiles:
      - "src/**/*.test.ts"
      - "src/**/__mocks__/*.ts"
