CountriesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: "name"
        AttributeType: "S"
    BillingMode: PAY_PER_REQUEST
    KeySchema: 
      - AttributeName: "name"
        KeyType: "HASH"
    TableName: countries-${self:provider.stage}
